//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 02/08/2018 21:23:27
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Tutorial.Resources
{
    using Windows.ApplicationModel.Resources;
    
    
    internal sealed partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Email is invalid."
        /// </summary>
        public static string EmailInvalid
        {
            get
            {
                return resourceLoader.GetString("EmailInvalid");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Name is invalid."
        /// </summary>
        public static string NameInvalid
        {
            get
            {
                return resourceLoader.GetString("NameInvalid");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Name is required."
        /// </summary>
        public static string NameRequired
        {
            get
            {
                return resourceLoader.GetString("NameRequired");
            }
        }
    }
}
