mklink /D "D:\Files\Library\Audio Controversial.非主流音乐" "\\box-a\F\Files\Library\Audio Controversial.非主流音乐"
mklink /D "D:\Files\Library\Audio Mainstream.主流音乐" "\\box-a\F\Files\Library\Audio Mainstream.主流音乐"
mklink /D "D:\Files\Library\Audio Show.节目音频" "\\box-a\F\Files\Library\Audio Show.节目音频"
mklink /D "D:\Files\Library\Audio Soundtrack.电影音乐" "\\box-a\F\Files\Library\Audio Soundtrack.电影音乐"

mklink /D "D:\Files\Library\Movies 3D.立体电影" "\\box-a\K\Files\Library\Movies 3D.立体电影"
mklink /D "D:\Files\Library\Movies 4K HDR.高动态范围电影" "\\box-a\J\Files\Library\Movies 4K HDR.高动态范围电影"
mklink /D "D:\Files\Library\Movies 4K HDR Overflow.高动态范围电影" "\\box-a\K\Files\Library\Movies 4K HDR Overflow.高动态范围电影"
mklink /D "D:\Files\Library\Movies Controversial.非主流电影" "\\box-a\K\Files\Library\Movies Controversial.非主流电影"
mklink /D "D:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]" "\\box-a\K\Files\Library\Movies Controversial.非主流电影[未抓取字幕]"
mklink /D "D:\Files\Library\Movies Disk.电影原盘" "\\box-a\K\Files\Library\Movies Disk.电影原盘"
mklink /D "D:\Files\Library\Movies Franchise.系列电影" "\\box-a\G\Files\Library\Movies Franchise.系列电影"
mklink /D "D:\Files\Library\Movies Mainstream 1.主流电影1" "\\box-a\G\Files\Library\Movies Mainstream 1.主流电影1"
mklink /D "D:\Files\Library\Movies Mainstream 2.主流电影2" "\\box-a\H\Files\Library\Movies Mainstream 2.主流电影2"
mklink /D "D:\Files\Library\Movies Mainstream 3.主流电影3" "\\box-a\I\Files\Library\Movies Mainstream 3.主流电影3"
mklink /D "D:\Files\Library\Movies Musical.音乐" "\\box-a\K\Files\Library\Movies Musical.音乐"
mklink /D "D:\Files\Library\Movies Temp 1" "\\box-a\G\Files\Library\Movies Temp 1"
mklink /D "D:\Files\Library\Movies Temp 2" "\\box-a\H\Files\Library\Movies Temp 2"
mklink /D "D:\Files\Library\Movies Temp 3" "\\box-a\I\Files\Library\Movies Temp 3"
mklink /D "D:\Files\Library\Movies Temp 4K HDR 1" "\\box-a\J\Files\Library\Movies Temp 4K HDR 1"
mklink /D "D:\Files\Library\Movies Temp 4K HDR 2" "\\box-a\K\Files\Library\Movies Temp 4K HDR 2"

mklink /D "D:\Files\Library\TV 4K HDR.高动态范围电视剧" "\\box-a\K\Files\Library\TV 4K HDR.高动态范围电视剧"
mklink /D "D:\Files\Library\TV Controversial.非主流电视剧" "\\box-a\K\Files\Library\TV Controversial.非主流电视剧"
mklink /D "D:\Files\Library\TV Documentary.记录电视剧" "\\box-a\K\Files\Library\TV Documentary.记录电视剧"
mklink /D "D:\Files\Library\TV Mainstream.主流电视剧" "\\box-a\L\Files\Library\TV Mainstream.主流电视剧"
mklink /D "D:\Files\Library\TV Mainstream Chinese.主流电视剧" "\\box-a\K\Files\Library\TV Mainstream Chinese.主流电视剧"
mklink /D "D:\Files\Library\TV Mainstream Overflow.主流电视剧" "\\box-a\K\Files\Library\TV Mainstream Overflow.主流电视剧"
mklink /D "D:\Files\Library\TV Tutorial.教程" "\\box-a\K\Files\Library\TV Tutorial.教程"
mklink /D "D:\Files\Library\TV Temp 1" "\\box-a\L\Files\Library\TV Temp 1"
mklink /D "D:\Files\Library\TV Temp 2" "\\box-a\K\Files\Library\TV Temp 2"

mklink /D "D:\Files\Library\MovieMetadata" "\\box-a\K\Files\Library\MovieMetadata"
mklink /D "D:\Files\Library\MovieMetadataBackup" "\\box-a\K\Files\Library\MovieMetadataBackup"
mklink /D "D:\Files\Library\MovieMetadataCache" "\\box-a\K\Files\Library\MovieMetadataCache"
mklink /D "D:\Files\Library\MovieMetadataFile" "\\box-a\K\Files\Library\MovieMetadataFile"
mklink /D "D:\Files\Library\MovieMetadataCacheBackup" "\\box-a\K\Files\Library\MovieMetadataCacheBackup"
mklink /D "D:\Files\Library\TVMetadata" "\\box-a\K\Files\Library\TVMetadata"
mklink /D "D:\Files\Library\TVMetadataCache" "\\box-a\K\Files\Library\TVMetadataCache"

mklink /D "D:\Files\Library\MovieSubtitle" "\\box-a\K\Files\Library\MovieSubtitle"
mklink /D "D:\Files\Library\TVSubtitle" "\\box-a\K\Files\Library\TVSubtitle"
