mklink /J "D:\Files\Library\TV Documentary.记录电视剧" "L:\Files\Library\TV Documentary.记录电视剧"
mklink /J "D:\Files\Library\TV Mainstream.主流电视剧" "L:\Files\Library\TV Mainstream.主流电视剧"
mklink /J "D:\Files\Library\TV Mainstream.主流电视剧[未抓取字幕]" "L:\Files\Library\TV Mainstream.主流电视剧[未抓取字幕]"
mklink /J "D:\Files\Library\TV Mainstream Overflow.主流电视剧" "K:\Files\Library\TV Mainstream Overflow.主流电视剧"
mklink /J "D:\Files\Library\TV Controversial.非主流电视剧" "F:\Files\Library\TV Controversial.非主流电视剧"

mklink /J "D:\Files\Library\Movies Franchise.系列电影" "G:\Files\Library\Movies Franchise.系列电影"
mklink /J "D:\Files\Library\Movies Franchise.系列电影[未抓取字幕]" "G:\Files\Library\Movies Franchise.系列电影[未抓取字幕]"
mklink /J "D:\Files\Library\Movies Mainstream 1.主流电影1" "G:\Files\Library\Movies Mainstream 1.主流电影1"
mklink /J "D:\Files\Library\Movies Mainstream 2.主流电影2" "H:\Files\Library\Movies Mainstream 2.主流电影2"
mklink /J "D:\Files\Library\Movies Mainstream 3.主流电影3" "I:\Files\Library\Movies Mainstream 3.主流电影3"
mklink /J "D:\Files\Library\Movies 4K HDR.高动态范围电影" "J:\Files\Library\Movies 4K HDR.高动态范围电影"
mklink /J "D:\Files\Library\Movies 4K HDR Overflow.高动态范围电影" "K:\Files\Library\Movies 4K HDR Overflow.高动态范围电影"

mklink /J "D:\Files\Library\Audio Controversial.非主流音乐" "F:\Files\Library\Audio Controversial.非主流音乐"
mklink /J "D:\Files\Library\Audio Mainstream.主流音乐" "F:\Files\Library\Audio Mainstream.主流音乐"
mklink /J "D:\Files\Library\Audio Show.节目音频" "F:\Files\Library\Audio Show.节目音频"
mklink /J "D:\Files\Library\Audio Soundtrack.电影音乐" "F:\Files\Library\Audio Soundtrack.电影音乐"
mklink /J "D:\Files\Library\Movies 3D.立体电影" "F:\Files\Library\Movies 3D.立体电影"
mklink /J "D:\Files\Library\Movies Controversial.非主流电影" "F:\Files\Library\Movies Controversial.非主流电影"
mklink /J "D:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]" "F:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]"
mklink /J "D:\Files\Library\Movies Musical.音乐" "F:\Files\Library\Movies Musical.音乐"
mklink /J "D:\Files\Library\Movies Disk.电影原盘" "F:\Files\Library\Movies Disk.电影原盘"
mklink /J "D:\Files\Library\TV 4K HDR.高动态范围电视剧" "F:\Files\Library\TV 4K HDR.高动态范围电视剧"
mklink /J "D:\Files\Library\TV Tutorial.教程" "F:\Files\Library\TV Tutorial.教程"

mklink /J "D:\Files\Library\MovieMetadata" "K:\Files\Library\MovieMetadata"
mklink /J "D:\Files\Library\MovieMetadataBackup" "K:\Files\Library\MovieMetadataBackup"
mklink /J "D:\Files\Library\MovieMetadataCache" "K:\Files\Library\MovieMetadataCache"
mklink /J "D:\Files\Library\MovieMetadataCacheBackup" "K:\Files\Library\MovieMetadataCacheBackup"
mklink /J "D:\Files\Library\TVMetadata" "K:\Files\Library\TVMetadata"
mklink /J "D:\Files\Library\TVMetadataCache" "K:\Files\Library\TVMetadataCache"

mklink /J "D:\Files\Library\MovieSubtitle" "K:\Files\Library\MovieSubtitle"
mklink /J "D:\Files\Library\TVSubtitle" "K:\Files\Library\TVSubtitle"
