mklink /J "D:\Files\Library\Audio Controversial.非主流音乐" "F:\Files\Library\Audio Controversial.非主流音乐"
mklink /J "D:\Files\Library\Audio Mainstream.主流音乐" "F:\Files\Library\Audio Mainstream.主流音乐"
mklink /J "D:\Files\Library\Audio Show.节目音频" "F:\Files\Library\Audio Show.节目音频"
mklink /J "D:\Files\Library\Audio Soundtrack.电影音乐" "F:\Files\Library\Audio Soundtrack.电影音乐"

mklink /J "D:\Files\Library\Movies 3D.立体电影" "K:\Files\Library\Movies 3D.立体电影"
mklink /J "D:\Files\Library\Movies 4K HDR.高动态范围电影" "J:\Files\Library\Movies 4K HDR.高动态范围电影"
mklink /J "D:\Files\Library\Movies 4K HDR Overflow.高动态范围电影" "K:\Files\Library\Movies 4K HDR Overflow.高动态范围电影"
mklink /J "D:\Files\Library\Movies Controversial.非主流电影" "K:\Files\Library\Movies Controversial.非主流电影"
mklink /J "D:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]" "K:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]"
mklink /J "D:\Files\Library\Movies Disk.电影原盘" "K:\Files\Library\Movies Disk.电影原盘"
mklink /J "D:\Files\Library\Movies Franchise.系列电影" "G:\Files\Library\Movies Franchise.系列电影"
mklink /J "D:\Files\Library\Movies Mainstream 1.主流电影1" "G:\Files\Library\Movies Mainstream 1.主流电影1"
mklink /J "D:\Files\Library\Movies Mainstream 2.主流电影2" "H:\Files\Library\Movies Mainstream 2.主流电影2"
mklink /J "D:\Files\Library\Movies Mainstream 3.主流电影3" "I:\Files\Library\Movies Mainstream 3.主流电影3"
mklink /J "D:\Files\Library\Movies Musical.音乐" "K:\Files\Library\Movies Musical.音乐"
mklink /J "D:\Files\Library\Movies Temp 1" "G:\Files\Library\Movies Temp 1"
mklink /J "D:\Files\Library\Movies Temp 2" "H:\Files\Library\Movies Temp 2"
mklink /J "D:\Files\Library\Movies Temp 3" "I:\Files\Library\Movies Temp 3"
mklink /J "D:\Files\Library\Movies Temp 4K HDR 1" "J:\Files\Library\Movies Temp 4K HDR 1"
mklink /J "D:\Files\Library\Movies Temp 4K HDR 2" "K:\Files\Library\Movies Temp 4K HDR 2"

mklink /J "D:\Files\Library\TV 4K HDR.高动态范围电视剧" "K:\Files\Library\TV 4K HDR.高动态范围电视剧"
mklink /J "D:\Files\Library\TV Controversial.非主流电视剧" "K:\Files\Library\TV Controversial.非主流电视剧"
mklink /J "D:\Files\Library\TV Documentary.记录电视剧" "K:\Files\Library\TV Documentary.记录电视剧"
mklink /J "D:\Files\Library\TV Mainstream.主流电视剧" "L:\Files\Library\TV Mainstream.主流电视剧"
mklink /J "D:\Files\Library\TV Mainstream Chinese.主流电视剧" "K:\Files\Library\TV Mainstream Chinese.主流电视剧"
mklink /J "D:\Files\Library\TV Mainstream Overflow.主流电视剧" "K:\Files\Library\TV Mainstream Overflow.主流电视剧"
mklink /J "D:\Files\Library\TV Tutorial.教程" "K:\Files\Library\TV Tutorial.教程"
mklink /J "D:\Files\Library\TV Temp 1" "L:\Files\Library\TV Temp 1"
mklink /J "D:\Files\Library\TV Temp 2" "K:\Files\Library\TV Temp 2"

mklink /J "D:\Files\Library\Metadata.All.Movies" "K:\Files\Library\Metadata.All.Movies"
mklink /J "D:\Files\Library\Metadata.All.Movies.Backup" "K:\Files\Library\Metadata.All.Movies.Backup"
mklink /J "D:\Files\Library\Metadata.All.Movies.Cache" "K:\Files\Library\Metadata.All.Movies.Cache"
mklink /J "D:\Files\Library\Metadata.All.Movies.CacheBackup" "K:\Files\Library\Metadata.All.Movies.CacheBackup"
mklink /J "D:\Files\Library\Metadata.All.Movies.File" "K:\Files\Library\Metadata.All.Movies.File"
mklink /J "D:\Files\Library\Metadata.All.Movies.Subtitles" "K:\Files\Library\Metadata.All.Movies.Subtitles"

mklink /J "D:\Files\Library\Metadata.All.TV" "K:\Files\Library\Metadata.All.TV"
mklink /J "D:\Files\Library\Metadata.All.TV.Cache" "K:\Files\Library\Metadata.All.TV.Cache"
mklink /J "D:\Files\Library\Metadata.All.TV.Subtitles" "K:\Files\Library\Metadata.All.TV.Subtitles"

mklink /J "D:\Files\Library\Metadata.Skin.Celebrities" "K:\Files\Library\Metadata.Skin.Celebrities"
mklink /J "D:\Files\Library\Metadata.Skin.Celebrities.Cache" "K:\Files\Library\Metadata.Skin.Celebrities.Cache"
mklink /J "D:\Files\Library\Metadata.Skin.Media" "K:\Files\Library\Metadata.Skin.Media"
mklink /J "D:\Files\Library\Metadata.Skin.Media.Cache" "K:\Files\Library\Metadata.Skin.Media.Cache"
