mklink /D "D:\Files\Library\TV Controversial.非主流电视剧" "\\box-l\F\Files\Library\TV Controversial.非主流电视剧"
mklink /D "D:\Files\Library\TV Documentary.记录电视剧" "\\box-l\F\Files\Library\TV Documentary.记录电视剧"
mklink /D "D:\Files\Library\TV Mainstream.主流电视剧" "\\box-l\F\Files\Library\TV Mainstream.主流电视剧"
mklink /D "D:\Files\Library\TV Mainstream.主流电视剧[未抓取字幕]" "\\box-l\F\Files\Library\TV Mainstream.主流电视剧[未抓取字幕]"

mklink /D "D:\Files\Library\Movies Mainstream.主流电影" "\\box-l\G\Files\Library\Movies Mainstream.主流电影"
mklink /D "D:\Files\Library\Movies Mainstream.主流电影[未抓取字幕]" "\\box-l\G\Files\Library\Movies Mainstream.主流电影[未抓取字幕]"

mklink /D "D:\Files\Library\Audio Controversial.非主流音乐" "\\box-l\H\Files\Library\Audio Controversial.非主流音乐"
mklink /D "D:\Files\Library\Audio Mainstream.主流音乐" "\\box-l\H\Files\Library\Audio Mainstream.主流音乐"
mklink /D "D:\Files\Library\Audio Show.节目音频" "\\box-l\H\Files\Library\Audio Show.节目音频"
mklink /D "D:\Files\Library\Audio Soundtrack.电影音乐" "\\box-l\H\Files\Library\Audio Soundtrack.电影音乐"
mklink /D "D:\Files\Library\Movies 3D.立体电影" "\\box-l\H\Files\Library\Movies 3D.立体电影"
mklink /D "D:\Files\Library\Movies 4K HDR.高动态范围电影" "\\box-l\H\Files\Library\Movies 4K HDR.高动态范围电影"
mklink /D "D:\Files\Library\Movies Controversial.非主流电影" "\\box-l\H\Files\Library\Movies Controversial.非主流电影"
mklink /D "D:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]" "\\box-l\H\Files\Library\Movies Controversial.非主流电影[未抓取字幕]"
mklink /D "D:\Files\Library\Movies Musical.音乐" "\\box-l\H\Files\Library\Movies Musical.音乐"
mklink /D "D:\Files\Library\Movies Disk.电影原盘" "\\box-l\H\Files\Library\Movies Disk.电影原盘"
mklink /D "D:\Files\Library\TV HDR.高动态范围电视剧" "\\box-l\H\Files\Library\TV HDR.高动态范围电视剧"
mklink /D "D:\Files\Library\TV Tutorial.教程" "\\box-l\H\Files\Library\TV Tutorial.教程"

mklink /D "D:\Files\Library\Movies Mainstream Temp1.主流电影1" "\\box-l\G\Files\Library\Movies Mainstream Temp1.主流电影1"
mklink /D "D:\Files\Library\Movies Mainstream Temp2.主流电影2" "\\box-l\H\Files\Library\Movies Mainstream Temp2.主流电影2"
mklink /D "D:\Files\Library\Movies Mainstream Temp3.主流电影3" "\\box-l\I\Files\Library\Movies Mainstream Temp3.主流电影3"
mklink /D "D:\Files\Library\Movies Mainstream Temp4.主流电影4" "\\box-l\J\Files\Library\Movies Mainstream Temp4.主流电影4"
mklink /D "D:\Files\Library\Movies Temp3.电影3" "\\box-l\I\Files\Library\Movies Temp3.电影3"
mklink /D "D:\Files\Library\Movies Temp3.2.电影3.2" "\\box-l\I\Files\Library\Movies Temp3.2.电影3.2"

mklink /D "D:\Files\Library\Movies Controversial Temp4.非主流电影4" "\\box-l\J\Files\Library\Movies Controversial Temp4.非主流电影4"
mklink /D "D:\Files\Library\Movies Encode4.电影4" "\\box-l\J\Files\Library\Movies Encode4.电影4"
mklink /D "D:\Files\Library\Movies Temp4.电影4" "\\box-l\J\Files\Library\Movies Temp4.电影4"
mklink /D "D:\Files\Library\Movies Temp4.2.电影4.2" "\\box-l\J\Files\Library\Movies Temp4.2.电影4.2"
mklink /D "D:\Files\Library\TV Temp4.电视剧4" "\\box-l\J\Files\Library\TV Temp4.电视剧4"

mklink /D "D:\Files\Library\MovieMetadata" "\\box-l\J\Files\Library\MovieMetadata"
mklink /D "D:\Files\Library\MovieMetadataBackup" "\\box-l\J\Files\Library\MovieMetadataBackup"
mklink /D "D:\Files\Library\MovieMetadataCache" "\\box-l\J\Files\Library\MovieMetadataCache"
mklink /D "D:\Files\Library\MovieMetadataCacheBackup" "\\box-l\J\Files\Library\MovieMetadataCacheBackup"
mklink /D "D:\Files\Library\TVMetadata" "\\box-l\J\Files\Library\TVMetadata"
mklink /D "D:\Files\Library\TVMetadataCache" "\\box-l\J\Files\Library\TVMetadataCache"

mklink /D "D:\Files\Library\MovieSubtitle" "\\box-l\J\Files\Library\MovieSubtitle"
mklink /D "D:\Files\Library\TVSubtitle" "\\box-l\J\Files\Library\TVSubtitle"
