mklink /J "D:\Files\Library\TV Controversial.非主流电视剧" "F:\Files\Library\TV Controversial.非主流电视剧"
mklink /J "D:\Files\Library\TV Documentary.记录电视剧" "F:\Files\Library\TV Documentary.记录电视剧"
mklink /J "D:\Files\Library\TV Mainstream.主流电视剧" "F:\Files\Library\TV Mainstream.主流电视剧"
mklink /J "D:\Files\Library\TV Mainstream.主流电视剧[未抓取字幕]" "F:\Files\Library\TV Mainstream.主流电视剧[未抓取字幕]"

mklink /J "D:\Files\Library\Movies Mainstream.主流电影" "G:\Files\Library\Movies Mainstream.主流电影"
mklink /J "D:\Files\Library\Movies Mainstream.主流电影[未抓取字幕]" "G:\Files\Library\Movies Mainstream.主流电影[未抓取字幕]"

mklink /J "D:\Files\Library\Audio Controversial.非主流音乐" "H:\Files\Library\Audio Controversial.非主流音乐"
mklink /J "D:\Files\Library\Audio Mainstream.主流音乐" "H:\Files\Library\Audio Mainstream.主流音乐"
mklink /J "D:\Files\Library\Audio Show.节目音频" "H:\Files\Library\Audio Show.节目音频"
mklink /J "D:\Files\Library\Audio Soundtrack.电影音乐" "H:\Files\Library\Audio Soundtrack.电影音乐"
mklink /J "D:\Files\Library\Movies 3D.立体电影" "H:\Files\Library\Movies 3D.立体电影"
mklink /J "D:\Files\Library\Movies 4K HDR.高动态范围电影" "H:\Files\Library\Movies 4K HDR.高动态范围电影"
mklink /J "D:\Files\Library\Movies Controversial.非主流电影" "H:\Files\Library\Movies Controversial.非主流电影"
mklink /J "D:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]" "H:\Files\Library\Movies Controversial.非主流电影[未抓取字幕]"
mklink /J "D:\Files\Library\Movies Musical.音乐" "H:\Files\Library\Movies Musical.音乐"
mklink /J "D:\Files\Library\Movies Disk.电影原盘" "H:\Files\Library\Movies Disk.电影原盘"
mklink /J "D:\Files\Library\TV HDR.高动态范围电视剧" "H:\Files\Library\TV HDR.高动态范围电视剧"
mklink /J "D:\Files\Library\TV Tutorial.教程" "H:\Files\Library\TV Tutorial.教程"

mklink /J "D:\Files\Library\Movies Mainstream Temp1.主流电影1" "G:\Files\Library\Movies Mainstream Temp1.主流电影1"
mklink /J "D:\Files\Library\Movies Mainstream Temp2.主流电影2" "H:\Files\Library\Movies Mainstream Temp2.主流电影2"
mklink /J "D:\Files\Library\Movies Mainstream Temp3.主流电影3" "I:\Files\Library\Movies Mainstream Temp3.主流电影3"
mklink /J "D:\Files\Library\Movies Mainstream Temp4.主流电影4" "J:\Files\Library\Movies Mainstream Temp4.主流电影4"
mklink /J "D:\Files\Library\Movies Temp3.电影3" "I:\Files\Library\Movies Temp3.电影3"
mklink /J "D:\Files\Library\Movies Temp3.2.电影3.2" "I:\Files\Library\Movies Temp3.2.电影3.2"

mklink /J "D:\Files\Library\Movies Controversial Temp4.非主流电影4" "J:\Files\Library\Movies Controversial Temp4.非主流电影4"
mklink /J "D:\Files\Library\Movies Encode4.电影4" "J:\Files\Library\Movies Encode4.电影4"
mklink /J "D:\Files\Library\Movies Temp4.电影4" "J:\Files\Library\Movies Temp4.电影4"
mklink /J "D:\Files\Library\Movies Temp4.2.电影4.2" "J:\Files\Library\Movies Temp4.2.电影4.2"
mklink /J "D:\Files\Library\TV Temp4.电视剧4" "J:\Files\Library\TV Temp4.电视剧4"

mklink /J "D:\Files\Library\MovieMetadata" "J:\Files\Library\MovieMetadata"
mklink /J "D:\Files\Library\MovieMetadataBackup" "J:\Files\Library\MovieMetadataBackup"
mklink /J "D:\Files\Library\MovieMetadataCache" "J:\Files\Library\MovieMetadataCache"
mklink /J "D:\Files\Library\MovieMetadataCacheBackup" "J:\Files\Library\MovieMetadataCacheBackup"
mklink /J "D:\Files\Library\TVMetadata" "J:\Files\Library\TVMetadata"
mklink /J "D:\Files\Library\TVMetadataCache" "J:\Files\Library\TVMetadataCache"

mklink /J "D:\Files\Library\MovieSubtitle" "J:\Files\Library\MovieSubtitle"
mklink /J "D:\Files\Library\TVSubtitle" "J:\Files\Library\TVSubtitle"
